name: Build and deploy Python + React app to Azure Web App - apollov2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Build Frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      - name: List frontend directory after build
        run: ls -R frontend


      # If using a Python backend in /backend, set this path accordingly
      # Move frontend build into backend or root static folder (adapt as needed)
      - name: Copy frontend build to backend static folder
        run: |
          mkdir -p static
          cp -r frontend/static/* static/

      # Set up Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 3.13 is in preview, 3.11 is recommended for prod

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Zip everything for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "frontend/*" ".git/*"
          cd ..

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'apollov2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E93F3EA0FACD40F8B7BDF3C2F6B9D07A }}
